# Generated by Django 2.0.5 on 2018-08-31 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ExtraProperty',
                'verbose_name_plural': 'ExtraProperty',
            },
        ),
        migrations.CreateModel(
            name='Gtw_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtw_id', models.CharField(default='', max_length=200, verbose_name='gtw_id')),
                ('rssi', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='rssi')),
                ('snr', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='snr')),
            ],
            options={
                'verbose_name': 'gtw_info',
                'verbose_name_plural': 'gtw_info',
            },
        ),
        migrations.CreateModel(
            name='Push_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.DecimalField(decimal_places=1, max_digits=20, verbose_name='ID')),
                ('deveui', models.CharField(default='', max_length=200, verbose_name='设备的EUI')),
                ('timestamp', models.CharField(default='', max_length=200, verbose_name='数据上报时间')),
                ('devaddr', models.DecimalField(decimal_places=1, max_digits=20, verbose_name='设备物理地址')),
                ('dataFrame', models.CharField(default='', max_length=200, verbose_name='设备业务原始数据(Base64编码)')),
                ('fcnt', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='fcnt')),
                ('port', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='port')),
                ('rssi', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='信号强度')),
                ('snr', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='信噪比')),
                ('freq', models.DecimalField(decimal_places=1, max_digits=20, verbose_name='freq')),
                ('devId', models.CharField(default='', max_length=200, verbose_name='devId')),
                ('appId', models.CharField(default='', max_length=200, verbose_name='应用编号')),
                ('sf_used', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='sf_used')),
                ('dr_used', models.CharField(default='', max_length=200, verbose_name='dr_used')),
                ('cr_used', models.CharField(default='', max_length=200, verbose_name='cr_used')),
                ('device_redundancy', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='device_redundancy')),
                ('time_on_air_ms', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='time_on_air_ms')),
                ('decrypted', models.CharField(default='', max_length=200, verbose_name='decrypted')),
                ('status', models.CharField(default='', max_length=200, verbose_name='status')),
                ('address', models.CharField(default='', max_length=200, verbose_name='address')),
                ('name', models.CharField(default='', max_length=200, verbose_name='name')),
                ('longitude', models.DecimalField(decimal_places=1, max_digits=15, verbose_name='longitude')),
                ('latitude', models.DecimalField(decimal_places=1, max_digits=15, verbose_name='latitude')),
            ],
            options={
                'verbose_name': '接收数据',
                'verbose_name_plural': '接收数据',
            },
        ),
        migrations.AddField(
            model_name='gtw_info',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lianshu_app.Push_data', verbose_name='绑定数据'),
        ),
        migrations.AddField(
            model_name='extraproperty',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lianshu_app.Push_data', verbose_name='绑定数据'),
        ),
    ]
