# Generated by Django 2.0.5 on 2018-08-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianshu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push_data',
            name='name',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='name'),
        ),
    ]
