# Generated by Django 2.0.5 on 2018-09-05 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lianshu_app', '0002_auto_20180831_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(default='', max_length=20, verbose_name='传感器类型 目前为0~2')),
                ('status', models.CharField(default='', max_length=20, verbose_name='传感器状态:0-正常 1-非正常')),
                ('rawdata', models.CharField(default='', max_length=50, verbose_name='数据采集的原始数据')),
                ('datatime', models.DateTimeField(verbose_name='数据采集时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '小压站下的传感器数据',
                'verbose_name_plural': '小压站下的传感器数据',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(default='', max_length=200, verbose_name='小站标识ID')),
                ('spillover', models.CharField(default='', max_length=200, verbose_name='满溢度(百分比)')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '小压站',
                'verbose_name_plural': '小压站',
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lianshu_app.Station', verbose_name='小压站'),
        ),
    ]
