# Generated by Django 2.0.5 on 2018-09-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianshu_app', '0003_auto_20180905_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='datatime',
            field=models.CharField(default='', max_length=100, verbose_name='数据采集时间'),
        ),
    ]
