# Generated by Django 2.0.5 on 2018-10-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianshu_app', '0005_auto_20181026_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraproperty',
            name='devId',
            field=models.CharField(default='', max_length=50, verbose_name='devId'),
        ),
        migrations.AddField(
            model_name='extraproperty',
            name='extra_id',
            field=models.CharField(default='', max_length=50, verbose_name='extra_id'),
        ),
        migrations.AddField(
            model_name='extraproperty',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='extraproperty',
            name='value',
            field=models.CharField(default='', max_length=50, verbose_name='value'),
        ),
    ]
