# Generated by Django 2.0.5 on 2018-10-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianshu_app', '0007_auto_20181029_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame_data',
            name='decode_list',
            field=models.CharField(default='', max_length=500, verbose_name='解码字符串list'),
        ),
    ]
