# Generated by Django 2.0.5 on 2018-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianshu_app', '0010_frame_data_sta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame_data',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
