# Generated by Django 2.0.5 on 2018-11-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianshu_app', '0011_frame_data_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame_data',
            name='status',
            field=models.IntegerField(default=0, verbose_name='是否在线'),
        ),
    ]
