# Generated by Django 2.0.5 on 2018-11-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianshu_app', '0012_auto_20181101_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame_data',
            name='count',
            field=models.IntegerField(default=0, verbose_name='今天第几箱垃圾(暂时默认为1)'),
        ),
    ]
