# Generated by Django 2.0.5 on 2018-11-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianshu_app', '0013_auto_20181101_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame_data',
            name='machine_id',
            field=models.CharField(default='', max_length=200, verbose_name='设备的EUI'),
        ),
        migrations.AlterField(
            model_name='frame_data',
            name='sta_id',
            field=models.CharField(default='', max_length=20, verbose_name='小压站标识'),
        ),
    ]
