# Generated by Django 2.0.5 on 2018-11-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lianshu_app', '0016_auto_20181102_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame_data',
            name='get_time',
            field=models.CharField(default='', max_length=500, verbose_name='上次收到数据时间'),
        ),
        migrations.AlterField(
            model_name='frame_data',
            name='online_time',
            field=models.CharField(default='', max_length=500, verbose_name='设备上线时间'),
        ),
    ]
